### ISSUE TITLE
CmdMess access voilation on Send

### ISSUE THREAD

**Issue by pmahend1** [kareldonk/QuantumGate#2]
When I run the CMDMess on 2 different machines I am able to connect the two machines. But when I do ```send UUID_of_remote "hello" ``` it throws exception `Exception thrown at 0x528E175F (ucrtbased.dll) in CmdMess.exe: 0xC0000005: Access violation reading location 0x00000001.`

Is it due to `auto m_Extender = std::make_shared<TestExtender::Extender>(nullptr);` being `nullptr`

I have all the libraries working well. This is we try to run in Debug/Release 32 mode and I have changed UUID at line `params.UUID.Set` of one machine so that two of them dont have same UUID

**Comment by kareldonk** [comment]
In CmdMess you should use the LUID (locally Unique Identifier) to send a message. When the peer connects you will see the LUID in the console. So the command is `send LUID "hello"`.
Note that CmdMess is a small and very simple test program to quickly test some features so it's not very polished and doesn't do rigorous checks of inputs. I'll see if I can repro the crash.

**Comment by kareldonk** [comment]
I was able to repro the issue; it was an issue that would occur in the 32-bit version of CmdMess due to an incorrect formatting option. You can see the changes in commit https://github.com/kareldonk/QuantumGate/commit/5798e29420101622883905e06cc26c205e3d8a66. The peer LUID is a 64-bit number and requires the `%llu` option instead of `%u`.

You can apply those two small changes yourself or sync with master branch to get the latest updates. Thanks for reporting.

Do keep in mind that the way CmdMess is written, it requires the peer LUID when using the `send` command. The reason for that is that peers can basically use the same UUID (Universally Unique Identifier) to connect to the local instance. For example, there are no limits that would prevent 2 other peers to use the same UUID to connect to you, or, for one peer to have two simultaneous connections to you. To distinguish between those two (or more) connections using the same UUID, QuantumGate automatically assigns every connection a LUID (Locally Unique Identifier). This LUID will always be different whenever the program is executed, even if the UUID is the same. So don't rely on having the same LUID each time for the same peer. 

Because there are no limits for a peer to use the same UUID as another peer, or to try to spoof another peer by using the same UUID, you should only rely on the UUID if authentication is enabled. That way it's impossible for someone to spoof another peer with the same UUID unless they also have their private (secret) key associated with that UUID. If they try to use someone else's UUID and don't have the private key, authentication will fail and the connection will not be accepted (if QuantumGate is configured to require authentication).

There are ways for an app or extender that you write to check if a connection to a peer is authenticated. For example, the [`GetPeerDetails`](https://github.com/kareldonk/QuantumGate/wiki/QuantumGate::Extender::GetPeerDetails) function returns that information and more.

**Comment by pmahend1** [comment]
I made these small changes and it works fine and thanks for the fix and clear explanation of the platform .

**Comment by kareldonk** [comment]
You're welcome. :)
