### ISSUE TITLE
Over Internet Connectivity

### ISSUE THREAD

**Issue by Katastrophos** [kareldonk/QuantumGate#3]
While experimenting with QuantumGate, i have run into a road block with the examples. I am unable to establish an over internet connection. with any example projects including TestApp. I am able to use for intranet. 

Listenermanager startup successful
Extendermanager starting...
Extendermanager startup successful
QuantumGate startup successful
[13/02/2019 04:29:13] Connecting to peer [**ipv6 or ipv4 address**]:9090
[13/02/2019 04:29:13] Socket error for peer 0.0.0.0:0 (LUID xxxxxxxxxxxxxxxxxx) (system : 10051 : A socket operation was attempted to an unreachable network.)
[13/02/2019 04:29:13] Disconnecting from endpoint 0.0.0.0:0 (LUID xxxxxxxxxxxxxxxxxxxxxxxxxxxx)
[13/02/2019 04:29:13] Could not connect to peer LUID xxxxxxxxxxxxxxxxxxxxxx (system : 10051 : A socket operation was attempted to an unreachable network.

Here's the setup: 
I have two Machines, each computer is in a different location,  one with an IPv6 address and the other with IPv4 address from the ISP's and the respective LAN addresses for each. 

Please advise

**Comment by kareldonk** [comment]
Did you change the IP address in the log you posted above to "0.0.0.0:0"? Could you provide some more details about the hardware/software setup? Which network card, version of Windows? If you go into the TestApp, in the menu `Local` - `Environment Info`, could you copy and paste the information you get there here?

**Comment by Katastrophos** [comment]
Sorry @kareldonk I was typing on my cellphone and it was difficult. Here is everything. I believe it has to do with the office network setup at PC-1 below 

**PC 1 Hardware**
Windows 10 pro x64

Realtek RTL8168/8111 PCI-E Gigabit Ethernet Adapter
**PC 2 Hardware**
Windows 10 pro x64
Intel(R) 82583V Gigabit Network Connection


The copy  paste from Environment Info
**PC-1**
```
Name:		{A6D94CD3-981B-48D7-B35C-6E5F7F5BED16}
Description:	Realtek PCIe GBE Family Controller
MAC Address:	50E549534C26
IP Addresses:	fe80::f43d:c640:3d80:f2d7, 10.151.5.97
Operational:	Yes

Name:		{73181406-BC31-11E8-AC05-806E6F6E6963}
Description:	Software Loopback Interface 1
MAC Address:	
IP Addresses:	::1, 127.0.0.1
Operational:	Yes
________________________________________________________

IP addresses:

Address:				fe80::f43d:c640:3d80:f2d7
On local interface:			Yes

Address:				10.151.5.97
On local interface:			Yes

Address:				::1
On local interface:			Yes

Address:				127.0.0.1
On local interface:			Yes
```
**PC 2**
```
Ethernet interfaces:

Name:		{CE739FD3-D2FE-42CD-A3FE-B4FD051704B5}
Description:	Intel(R) 82583V Gigabit Network Connection
MAC Address:	50465D652917
IP Addresses:	2600:1700:e520:17e0::6d4, 2600:1700:e520:17e0:68de:a190:1dc3:d349, 2600:1700:e520:17e0:1c21:ef5e:5468:9b88, fe80::68de:a190:1dc3:d349, 192.168.1.67
Operational:	Yes

Name:		{FB85BCD5-DB9B-4B66-8335-84A5F1BACB47}
Description:	VMware Virtual Ethernet Adapter for VMnet1
MAC Address:	005056C00001
IP Addresses:	fe80::5956:c266:788d:c8f0, 169.254.200.240
Operational:	Yes

Name:		{11D24258-49A6-443E-8E26-D27896FA9879}
Description:	VMware Virtual Ethernet Adapter for VMnet8
MAC Address:	005056C00008
IP Addresses:	fe80::8010:9f86:7738:66b, 169.254.6.107
Operational:	Yes

Name:		{440EB9BC-485D-4484-B8B1-31A9B7891CB4}
Description:	TAP-ProtonVPN Windows Adapter V9
MAC Address:	00FF440EB9BC
IP Addresses:	fe80::86b:6076:6ae9:d2dd, 169.254.210.221
Operational:	No

Name:		{AB5C0493-346A-4E12-BFD5-085DA9E21D31}
Description:	TAP-Windows Adapter V9
MAC Address:	00FFAB5C0493
IP Addresses:	fe80::7c28:72ce:9787:ba6, 169.254.11.166
Operational:	No

Name:		{551BC53D-09D7-11E8-A003-806E6F6E6963}
Description:	Software Loopback Interface 1
MAC Address:	
IP Addresses:	::1, 127.0.0.1
Operational:	Yes

Name:		{2CA7312B-E35E-4596-8D07-DA1F87120E2D}
Description:	Hyper-V Virtual Ethernet Adapter
MAC Address:	E2155FD0E974
IP Addresses:	fe80::2dd0:93cd:b4fc:ed45, 172.17.187.177
Operational:	Yes
________________________________________________________

IP addresses:

Address:				2600:1700:e520:17e0::6d4
On local interface:			Yes

Address:				2600:1700:e520:17e0:68de:a190:1dc3:d349
On local interface:			Yes

Address:				2600:1700:e520:17e0:1c21:ef5e:5468:9b88
On local interface:			Yes

Address:				fe80::68de:a190:1dc3:d349
On local interface:			Yes

Address:				192.168.1.67
On local interface:			Yes

Address:				fe80::5956:c266:788d:c8f0
On local interface:			Yes

Address:				169.254.200.240
On local interface:			Yes

Address:				fe80::8010:9f86:7738:66b
On local interface:			Yes

Address:				169.254.6.107
On local interface:			Yes

Address:				::1
On local interface:			Yes

Address:				127.0.0.1
On local interface:			Yes

Address:				fe80::2dd0:93cd:b4fc:ed45
On local interface:			Yes

Address:				172.17.187.177
On local interface:			Yes

**Comment by kareldonk** [comment]
So how are you trying to connect, from PC1 to PC2? Or PC2 to PC1? And when you try to connect using the TestApp, what IP address do you specify?

Since the PCs are on different locations and you're trying to connect over the Internet, you're going to need to know the public IP address of the PC you are connecting to, and not the address on the local LAN. In addition, you will have to make sure that the router at the destination location is configured to allow outside connections to the PC on the internal network. 

For example, let's say you try to connect from PC1 to PC2, then you would need to know the public IP address for PC2. You can find this out by opening the website [https://www.whatismyip.com/](https://www.whatismyip.com/) on PC2. Once you know the public IP of PC2, you can use that IP to connect on PC1. Make sure the TestApp is running and initialized on both PCs before trying to connect. Then on PC1, try to connect to PC2 using PC2's public IP.

On addition, the router/firewall behind which PC2 is located will need to forward incoming connections on the port you are using (in this case 9090) to PC2. Also, locally on PC2, you also need to configure Windows Firewall to allow TCP/IP connections to PC2 on port 9090. To trouble shoot, make sure you can connect to PC2 from another PC on the same local network as PC2. If this works, then you'll know that if PC1 cannot connect to PC2, it has to be because the incoming connection may be blocked by the router/modem/firewall behind which PC2 is located.

Currently QuantumGate does not automatically configure the Windows Firewall, and if your PC is behind a NAT, does not try to configure the NAT to open/forward any ports; you have to do this manually.

**Comment by Katastrophos** [comment]
I figured a way to get it done. 👍
