### ISSUE TITLE
problems with building, unresolved external symbols

### ISSUE THREAD

**Issue by constantinfuerst** [kareldonk/QuantumGate#4]
Hello,
for the last two afternoons I've been trying to get QuantumGate up and running but had no luck.
I get these errors and can't make much sense of them, my only idea is that openssl nowadays has split its libraries into libcrypto and libssl. These errors all seem to mean that the SSL part of openssl isn't found in the library but I have no clue how to fix this. I am using the most current version of OpenSSL, downloaded and compiled (with Configure: VC-WIN64A no-asm no-shared no-idea, for some reason it would not compile without these settings) today.

![image](https://user-images.githubusercontent.com/31138134/60046172-380b7500-96b6-11e9-8fd3-58c49acd4177.png)

**Comment by kareldonk** [comment]
Hi, those errors seem related to OpenSSL. For clarification, QuantumGate doesn't use libssl; only libcrypto. I don't know how you built OpenSSL, but you should follow the instructions for the Windows build in [this answer on StackOverflow](https://stackoverflow.com/a/45495686). 

Since QuantumGate is configured to look for specific naming of the libcrypto library and DLL (see the [readme](https://github.com/kareldonk/QuantumGate/blob/master/README.md) for details), you will need to specify the output filenames before building OpenSSL. You should not rename the library and DLL files after building OpenSSL. You can specify the library output names in the [`build.info`](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/build.info) file in the OpenSSL main folder. You will need to specify the names on lines 89 and 90:
```
 SHARED_NAME[libcrypto]=libcrypto-{- $sover_filename -}{- $target{multilib} -}
 SHARED_NAME[libssl]=libssl-{- $sover_filename -}{- $target{multilib} -}
```
Change to the following for 64 bit builds (for 32 bit builds change the 64 to 32 in the names):
```
 SHARED_NAME[libcrypto]=libcrypto64
 SHARED_NAME[libssl]=libssl64
```
Then run the build steps from the StackOverflow answer. 

Also note that these instructions work up to OpenSSL version 1.1.1. Make sure you use that version.

Once you've managed to build OpenSSL, you can then build QuantumGate using Visual Studio. Open the QuantumGate.sln file in the project root in Visual Studio and issue the build command. You may need to also tell Visual Studio where it can find the header include files and library files for the various dependencies including OpenSSL (configure include paths).

**Comment by constantinfuerst** [comment]
Thanks for the quick and informative answer. I will give this a try tomorrow.
Thank you again!

**Comment by kareldonk** [comment]
No problem and let me know how it goes.

**Comment by constantinfuerst** [comment]
I recompiled using the version and tutorial you supplied but the name change didn't have any effect on the output for some reason. I got tired of it and just changed the library include name in stdafx.h to libcrypto.lib and then it compiled successfully. You might consider making openssl-1.1.1 a requirement and not a minimum because latest version wouldn't work with QuantumGate.
Thanks for your help and greetings from germany!

**Comment by kareldonk** [comment]
Thanks for the update. It seems they did change some of the build scripts in the latest versions of OpenSSL so that might be the cause of issues. I haven't used the latest version yet myself so have no experience with that but perhaps you have to build it in a different way. I will however be updating this project to use the latest version of OpenSSL in the near future when I push the latest version to the master branch.

**Comment by kareldonk** [comment]
I want to add that I tested OpenSSL version 1.1.1c with the same above instructions as 1.1.1a and it works. I noticed that the master development branch at OpenSSL's repo is currently at version 3.0.0 and the build scripts for that have changed. I haven't tested that version as it is not officially released yet.

**Comment by kareldonk** [comment]
For build instructions for OpenSSL 3.0.0 see issue https://github.com/kareldonk/QuantumGate/issues/9. Only use OpenSSL 3.0.0 with QuantumGate version 0.3.0.0 (currently not yet released).
